# Generated by Django 5.1.1 on 2026-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260405_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_migration',
            field=models.BooleanField(default=False),
        ),
    ]
