version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sub_tracker_db
    restart: always
    environment:
      - POSTGRES_DB=Subscription_Tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5678:5432"  # Map local port 5678 to internal Postgres port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sub_tracker_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: