[mypy]
python_version = 3.13
plugins = mypy_django_plugin.main
ignore_missing_imports = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unused_configs = True
exclude = (?x)(
    ^venv/
    | ^staticfiles/
    | ^pytest-cache-files-.*/
    | /migrations/
  )

[mypy.plugins.django-stubs]
django_settings_module = config.settings
