# Generated by Django 5.1.1 on 2026-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('streaming', 'Streaming'), ('music', 'Music'), ('software', 'Software'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_renewal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
