# Generated by Django 5.1.1 on 2026-04-13 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0002_subscription_category_subscription_next_renewal"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionImportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=50)),
                ("account_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        default="succeeded",
                        max_length=20,
                    ),
                ),
                ("requested_transaction_count", models.PositiveIntegerField(default=0)),
                ("ingested_transactions", models.PositiveIntegerField(default=0)),
                ("duplicate_transactions", models.PositiveIntegerField(default=0)),
                ("invalid_transactions", models.PositiveIntegerField(default=0)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="transactionevidence",
            name="dedupe_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="transactionevidence",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="subscriptions.transactionimportrun",
            ),
        ),
        migrations.AddField(
            model_name="transactionevidence",
            name="normalized_merchant_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="transactionevidence",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
