# Generated by Django 5.1.1 on 2026-04-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0003_transactionimportrun_transactionevidence_dedupe_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailScanRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="imap", max_length=50)),
                ("mailbox", models.CharField(default="INBOX", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        default="succeeded",
                        max_length=20,
                    ),
                ),
                ("scanned_message_count", models.PositiveIntegerField(default=0)),
                ("matched_message_count", models.PositiveIntegerField(default=0)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="EmailSubscriptionLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=255)),
                ("sender_name", models.CharField(blank=True, default="", max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(max_length=255)),
                ("snippet", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField()),
                ("confidence_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("dismissed", "Dismissed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_headers", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="subscriptions.emailscanrun",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-received_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="emailsubscriptionlead",
            constraint=models.UniqueConstraint(fields=("user", "message_id"), name="uniq_email_subscription_lead_per_user"),
        ),
    ]
