# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_emailscanrun_emailsubscriptionlead"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsubscriptionlead",
            name="cleaned_body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subscriptioncandidate",
            name="source_type",
            field=models.CharField(
                choices=[("transactions", "Transactions"), ("email_receipt", "Email receipt")],
                default="transactions",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="subscriptioncandidate",
            name="source_email_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_candidates",
                to="subscriptions.emailsubscriptionlead",
            ),
        ),
        migrations.AddField(
            model_name="subscriptioncandidate",
            name="billing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptioncandidate",
            name="likely_renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptioncandidate",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptioncandidate",
            name="parser_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="subscriptioncandidate",
            name="raw_entity_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
